import os
import pytest
from unittest.mock import patch

# Load .env values so AssemblyAI, Google Speech and OpenAI keys are available during the test
try:
    from dotenv import dotenv_values
    env_path = os.path.join(os.path.dirname(__file__), '..', '.env')
    env = dotenv_values(env_path)
    for k, v in env.items():
        if v is not None and k not in os.environ:
            os.environ[k] = v
except Exception:
    pass

from src.models.voice_transcriber import VoiceTranscriber
from src.models.free_translator import FreeTranslator


def _load_fixture_bytes(name: str) -> bytes:
    path = os.path.join('tests', 'fixtures', name)
    with open(path, 'rb') as f:
        return f.read()


@pytest.mark.integration
@pytest.mark.skipif(os.getenv('RUN_INTEGRATION') != '1', reason='integration tests disabled')
def test_russian_voice_transcription_and_translation():
    """Transcribe a Russian voice OGG and translate to English.

    The fixture ``russian_voice.ogg`` is generated by ``scripts/generate_russian_tts.py``.
    """
    fixture_path = os.path.join('tests', 'fixtures', 'russian_voice.ogg')
    if not os.path.exists(fixture_path):
        pytest.skip(f"Voice fixture not found: {fixture_path}")

    audio_bytes = _load_fixture_bytes('russian_voice.ogg')

    vt = VoiceTranscriber()
    # Mock the download step to return our fixture bytes
    with patch.object(VoiceTranscriber, '_download_voice_file', return_value=audio_bytes):
        result = vt.transcribe_voice_message_with_confidence('FAKE_ID', confidence_threshold=0.65)

    assert result is not None, "Transcription failed"
    transcription = result.text
    assert transcription.strip(), "Empty transcription"

    # Translate to English using FreeTranslator (Google Translate)
    translator = FreeTranslator()
    translated = translator.translate_text(transcription, 'en', 'auto')
    assert translated and not translated.startswith('❌'), f"Translation failed: {translated}"
